#pragma once
#include "../core/context.hpp"
#include "commandpool.hpp"
#include "devices.hpp"
#include "swapchain.hpp"
#include "drawer.hpp"
#include "descriptor.hpp"
#include "renderpass.hpp"
#include "graphicspipeline.hpp"
#include "imageview.hpp"
#include "buffers.hpp"
#include <stdexcept>
#include <iostream>
#include <set>
#include <cstdlib>
#include <algorithm>
#include <vector>
#include <array>
#include <string>

void createInstance();
void createSurface();
void initVulkan();
